
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 08 10:51:56 CDT 2019
//----------------------------------------------------

package AnalizadorLS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMREAL = 8;
  public static final int PUNYCO = 13;
  public static final int EOF = 0;
  public static final int IF = 2;
  public static final int LLAVEC = 11;
  public static final int ELSE = 5;
  public static final int ID = 6;
  public static final int IGUAL = 12;
  public static final int LLAVEA = 10;
  public static final int error = 1;
  public static final int DATO = 9;
  public static final int OPREL = 7;
  public static final int PARC = 4;
  public static final int PARA = 3;
}

